jobs:
  - name: gha-sts-secrets
    max_in_flight: 1
    plan:
      - get: docker-poc-gha-ecr
        trigger: true
        passed: 
          - management-dev
      - .: (( inject meta.plan.terraform-bootstrap ))
        params:
          TF_DIR: "gha_sts_secrets"
      - .: (( inject meta.plan.terraform-apply ))
        params:
          TF_WORKSPACE: "management"
          TF_DIR: "gha_sts_secrets"
      - .: (( inject meta.plan.terraform-plan ))
        params:
          TF_WORKSPACE: "management"
          TF_DIR: "gha_sts_secrets"
