jobs:
  - name: management-dev
    max_in_flight: 1
    plan:
      - get: docker-poc-gha-ecr
        trigger: true
      - .: (( inject meta.plan.terraform-bootstrap ))
        params:
          TF_DIR: "ecr"
      - .: (( inject meta.plan.terraform-apply ))
        params:
          TF_DIR: "ecr"
      - .: (( inject meta.plan.terraform-plan ))
        params:
          TF_DIR: "ecr"
