jobs:
  - name: docker-poc-gha-ecr-pr
    plan:
      - get: docker-poc-gha-ecr-pr
        trigger: true
        version: every
      - put: docker-poc-gha-ecr-pr
        params:
          path: docker-poc-gha-ecr-pr
          status: pending
      - .: (( inject meta.plan.terraform-bootstrap ))
        input_mapping:
          docker-poc-gha-ecr: docker-poc-gha-ecr-pr
      - .: (( inject meta.plan.terraform-plan ))
        input_mapping:
          docker-poc-gha-ecr: docker-poc-gha-ecr-pr
        params:
          TF_WORKSPACE: "management"
          DETAILED_EXITCODE: ""
        on_failure:
          put: docker-poc-gha-ecr-pr
          params:
            path: docker-poc-gha-ecr-pr
            status: failure
        on_success:
          put: docker-poc-gha-ecr-pr
          params:
            path: docker-poc-gha-ecr-pr
            status: success
